"""Markdown renderer — for GitHub wikis, Notion, internal docs."""

from __future__ import annotations

from haak_anvil.core.models import Finding, ReportBundle
from haak_anvil.core.severity import Severity
from haak_anvil.renderers.base import RendererBase

_SEV_BADGE = {
    Severity.CRITICAL: "🔴 CRITICAL",
    Severity.HIGH: "🟠 HIGH",
    Severity.MEDIUM: "🟡 MEDIUM",
    Severity.LOW: "🔵 LOW",
    Severity.INFO: "⚪ INFO",
}


def _md_escape(s: str) -> str:
    """Neutraliza caracteres que rompen o inyectan estructura Markdown.

    Hostnames, OS y banners provienen del activo escaneado — input no
    confiable que puede contener `|`, saltos de línea o backslashes.
    """
    return (
        s.replace("\\", "\\\\")
        .replace("|", "\\|")
        .replace("\r", " ")
        .replace("\n", " ")
    )


class MarkdownRenderer(RendererBase):
    extension = "md"

    def render(self, bundle: ReportBundle) -> str:
        eng = bundle.engagement
        out: list[str] = []

        # ----- header -----
        out.append(f"# Pentest Report — {eng.client_name}")
        out.append("")
        out.append(f"**Engagement ID:** `{eng.id}`")
        out.append(f"**Methodology:** {eng.methodology}")
        if eng.period_start or eng.period_end:
            out.append(
                f"**Window:** {eng.period_start or '?'} → {eng.period_end or '?'}"
            )
        out.append(f"**Analyst:** {eng.analyst}")
        out.append(f"**Generated:** {bundle.generated_at.isoformat()}")
        out.append("")
        out.append(f"**Scope:** {eng.scope}")
        out.append("")
        out.append("---")
        out.append("")

        # ----- executive summary -----
        out.append("## Executive summary")
        out.append("")
        out.append(f"- **Total assets analyzed:** {len(bundle.assets)}")
        out.append(f"- **Total findings:** {len(bundle.findings)}")
        for sev in [
            Severity.CRITICAL,
            Severity.HIGH,
            Severity.MEDIUM,
            Severity.LOW,
            Severity.INFO,
        ]:
            count = bundle.severity_breakdown[sev.value]
            out.append(f"  - {_SEV_BADGE[sev]}: {count}")
        out.append("")

        # ----- findings sorted by severity -----
        out.append("## Findings")
        out.append("")
        for f in bundle.findings_sorted():
            out.extend(self._render_finding(f))

        # ----- assets table -----
        out.append("## Assets")
        out.append("")
        out.append("| Address | Hostname | OS | Open ports |")
        out.append("|---|---|---|---|")
        for a in bundle.assets:
            out.append(
                f"| `{_md_escape(a.address)}` "
                f"| {_md_escape(a.hostname) if a.hostname else '—'} "
                f"| {_md_escape(a.os) if a.os else '—'} "
                f"| {a.open_port_count} |"
            )
        out.append("")

        # ----- footer -----
        out.append("---")
        out.append(
            f"_Generated by `{bundle.generator}` v{bundle.generator_version} — "
            f"Haak Cybersecurity Consulting (haak.com.mx)_"
        )
        out.append("")
        return "\n".join(out)

    @staticmethod
    def _render_finding(f: Finding) -> list[str]:
        out: list[str] = []
        out.append(f"### {_SEV_BADGE[f.severity]} — {_md_escape(f.title)}")
        out.append("")
        meta = []
        if f.asset:
            meta.append(f"**Asset:** `{f.asset}`")
        if f.port:
            meta.append(f"**Port:** {f.port}/{f.protocol or 'tcp'}")
        if f.cvss:
            meta.append(f"**CVSS {f.cvss.version}:** {f.cvss.score}")
        meta.append(f"**Tool:** `{f.tool}`")
        out.append(" · ".join(meta))
        out.append("")
        if f.description:
            out.append(f.description.strip())
            out.append("")
        if f.impact:
            out.append("**Impact:**")
            out.append("")
            out.append(f.impact.strip())
            out.append("")
        if f.remediation:
            out.append("**Remediation:**")
            out.append("")
            out.append(f.remediation.strip())
            out.append("")
        if f.cve:
            out.append(f"**CVE:** {', '.join(f.cve)}")
        if f.cwe:
            out.append(f"**CWE:** {', '.join(f.cwe)}")
        if f.references:
            out.append("**References:**")
            for r in f.references:
                out.append(f"- {r}")
        out.append("")
        out.append("---")
        out.append("")
        return out
